### PR TITLE
Support matching recordings using a URI regex

### PR DESCRIPTION
**Pull request by sjmadsen**
This PR revives the work that @epologee started in #24. I cherry picked his commits, then made additional changes to address the suggestions made by @dstnbrkr.

### CODE REVIEW

**Comment by dstnbrkr** [comment]
Looks good - thanks for reviving. Those two equality unit tests are failing it seems.

**Comment by sjmadsen** [comment]
I suspected there might be something wrong. The day job blocks Travis CI (who knows why).

Pretty sure the unit tests pass when I run it through Xcode, but I'll investigate and get a fix pushed up.

**Comment by dstnbrkr** [comment]
Excellent! Thanks for adding this feature!

**Comment by epologee** [comment]
Thanks @sjmadsen!

**Pull request merged**
